// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		byte numOfRands = Byte.parseByte(args[0]); 
		int greater = 0, lower = 0;// number of random values to generate
		for (byte i = 0; i < numOfRands; i++) {
			double rand = Math.random();
			if (rand >= 0.5) {
				greater++;
			} else {
				lower++;
			}
		}
		if (greater==0 || lower==0) {
			System.out.println("> 0.5: "+ greater +"  times");
			System.out.println("<= 0.5: "+ lower +"times");
		}
		else {
			System.out.println("> 0.5: "+ greater +"  times");
			System.out.println("<= 0.5: "+ lower +" times");
			System.out.println("Ratio:  " + (double)greater/lower);
		}

	}
}

